### ISSUE TITLE
Incompatible with Levels module

### ISSUE THREAD

**Issue by TheJazziestCat** [BoltsJ/sensor-sight#4]
When the Levels module is active, Sensor Sight does not work. When a player has their token selected, they cannot see other tokens. When they deselect their token, other tokens reappear, but when they mouse over one of those tokens, it disappears again. They can reselect and deselect their own token again to repeat the behavior.

Sensor Sight also only functions when Fog Exploration is turned on and the enemy tokens are in an explored area.

Foundry version 9 build 255, Lancer version 1.1.0, Levels version 2.5.3, Sensor Sight version 3.1

**Comment by BoltsJ** [comment]
Could you add the versions of foundry, sensor sight, levels, and the lancer system to your report. Thanks!

**Comment by Orionox** [comment]
getting the same issue
